<a href="https://colab.research.google.com/github/Kaushal-Top5699/tensorflow_08/blob/main/tensorflow_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

# **Tensorflow and Numpy Compatibility**

In [3]:
# Converting numpy array into a tensor.
A = tf.constant(np.array([1, 2, 3, 4]))
A

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [4]:
# Converting tensor back to numpy.
print(np.array(A))
print(type(np.array(A)))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# Another way to convert numpy into tensor.
B = A.numpy() 
print(B)
print(type(A.numpy()))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
B[0], B[-1]

(1, 4)

In [7]:
# dtypes of each are not the same.
numpy_A = tf.constant(np.array([1., 2., 3., 4.])) # Tensor from numpy is float64
tensor_A = tf.constant([1., 2., 3., 4.]) # Tensor directly created is float32

numpy_A.dtype, tensor_A.dtype

(tf.float64, tf.float32)

# **Finding access to GPUs**

In [11]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

GPUs and TPUs are much faster than CPUs. 

In [14]:
!nvidia-smi

Wed Mar 15 22:01:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    28W /  70W |    335MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------